### ISSUE TITLE
Goal: Nuon v2 Price Feed

### ISSUE THREAD

**Issue by Jarryd-pretorius** [trufnetwork/node#699]
# [Specs](https://docs.google.com/document/d/1z1hnqtZxsIl5m6ZZkBNDkkirNH5GZAoot2QIYcfvnnA/edit?tab=t.0)

# Blocked by
- https://github.com/truflation/tsn/issues/547

# Problem:
## Truf-data-provider:
- [x] https://github.com/trufnetwork/truf-data-provider/issues/348
- [x] https://github.com/trufnetwork/truf-data-provider/issues/349
- [x] https://github.com/trufnetwork/truf-data-provider/issues/350
- [x] https://github.com/trufnetwork/truf-data-provider/issues/351
- [x] https://github.com/trufnetwork/truf-data-provider/issues/352
- [x] https://github.com/trufnetwork/truf-data-provider/issues/365
- [x] https://github.com/trufnetwork/truf-data-provider/issues/371
- [x] https://github.com/trufnetwork/truf-data-provider/issues/372
- [x] https://github.com/trufnetwork/truf-data-provider/issues/375

## SDK-Js:
- [x] https://github.com/trufnetwork/sdk-js/issues/25

## ChainLink/EVM:
- [x] https://github.com/trufnetwork/truf-data-provider/issues/353

**Comment by markholdex** [comment]
log of the call with @itscameronlee:

- presented the solution we developed
- agreed that Nuon team will take over and start implementing the EVM contract on their end following the docs: https://github.com/trufnetwork/evm-contracts
- Cam will pass the docs to Doggo and do an introduction to him 
- If information will be missing or unclear, we will assist

---

This goal will be closed once the remaining Problem is solved:
- https://github.com/trufnetwork/sdk-js/issues/25

**Comment by MicBun** [comment]
Since all the problems have been resolved, I will close the issue.
