### ISSUE TITLE
Problem: Oracle contract is not deployed

### ISSUE THREAD

**Issue by outerlook** [trufnetwork/node#757]

**Comment by rsoury** [comment]
@outerlook - Can we deploy the Smart Contract with the code logic stored in a constant - then provide this constant on each request.

ie. `const LOGIC = "insert_js_code_dynamically"` -- via search and replace?

This is to prevent the callers from passing the logic to EVM Contracts.

**Comment by outerlook** [comment]
Note the contract has been deployed here: https://sepolia.etherscan.io/address/0x34c81dd71457084dae8e05e713ff8323a543dc5c#code

I'll wait for the attached PR to be approved so this issue can be closed, but the behavior should not change significantly

**Comment by outerlook** [comment]
although they are deployed, I'm not sure if I should put their address on the `evm-contracts` repo until we figure out who is the owner of the contract (truflation or trufnetwork?)
